### PR TITLE
64-bit engine support

### PR DESCRIPTION
**Pull request by fatcerberus**
As well as a few other fixes.  Since minisphere 1.1 will be a 64-bit engine, I figured we may as we add support now. :smile: 

I do wish I had checked GitHub before coding in the 64-bit support though, I forgot you were doing refactoring and ended up having the merge your stuff in, causing a massive merge conflict in the Designer file for the settings dialog.  :disappointed_relieved: Hopefully I didn't break anything in the process of resolving it...

### CODE REVIEW

**Comment by Radnen** [comment]
I'm not sure I want to merge this into master. I'll have to make a new branch just to see if things are ok.

**Comment by fatcerberus** [comment]
That's odd, it worked for me with casio's minisphere pull request.  Maybe your GitHub install is borked.

**Comment by fatcerberus** [comment]
Note that I did test it myself afterwards, and fixed a few bugs, e.g. the engine selector was broken due to the presets being moved and the Presets folder is now created at compile time.

Most of the conflicts were just labels being moved around and such.  Nothing else conflicted except for EditorSettings.Designer.cs.  But it's good that you're testing it too. :smiley:

**Comment by fatcerberus** [comment]
Did you ever get around to testing this change?  No problem if you didn't, I just figured I'd ask since I saw you just published a commit.

**Pull request closed without merging**
